package com.relatorio.transporte.repository.sqlserver;

import com.relatorio.transporte.entity.sqlserver.ConhecimentoEntity;
import com.relatorio.transporte.entity.sqlserver.ConhecimentoProjection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;
import org.springframework.data.repository.query.Param;

import java.util.List;

@org.springframework.stereotype.Repository
public interface ConhecimentoRepository extends Repository<ConhecimentoEntity, Integer> {

    @Query(value = """
    WITH Devolucao AS (
        SELECT
            LOGDEV.LG317_ID_CONHECIMENTO,
            MIN(LOGDEV.LG317_DATA_HORA) AS INICIO_DEVOLUCAO,
            MAX(LOGDEV.LG317_DATA_HORA) AS FINAL_DEVOLUCAO
        FROM LOG.DBO.LG317_DEVOLUCAO_EXTERNA LOGDEV WITH(NOLOCK)
        WHERE LOGDEV.LG317_DATA_HORA >= DATEADD(DAY, -:dias, GETDATE())
        GROUP BY LOGDEV.LG317_ID_CONHECIMENTO
    )
    SELECT
        CONH1.CP04_ID AS CONHECIMENTO,
        CASE CONH1.CP04_STATUS
            WHEN 23 THEN 'CANCELADO'
            WHEN 22 THEN 'CONCLUIDO SAIDA'
            WHEN 1 THEN 'EM DIGITAÇÃO'
            WHEN 5 THEN 'CONCLUIDO'
            WHEN 17 THEN 'EM VIAGEM'
            ELSE 'OUTROS'
        END AS STATUS_CONHECIMENTO,
        CONCAT(CONH1.CP04_ID_FILIAL,' - ',FILIAL.CD23_DESC) AS FILIAL,
        CASE CONH1.CP04_ID_TIPO
            WHEN 7 THEN '7 - CLIENTE EXTERNO'
            WHEN 8 THEN '8 - VENDA ABASTECIMENTO'
            WHEN 23 THEN '23 - ATACAREJO RETIRADA'
            ELSE 'OUTROS'
        END AS TIPO_CONHECIMENTO,
        CASE VEIC.CD94_CLASSIFICACAO
            WHEN 1 THEN '1 - PROPRIO'
            WHEN 2 THEN '2 - AGREGADO'
            WHEN 3 THEN '3 - TERCEIROS'
            ELSE 'DESCONHECIDO'
        END AS CLASSIFICACAO_MOTORISTA,
        CONCAT(CONH1.CP04_ID_MOTORISTA,' - ',MOTO.CD93_NOME) AS MOTORISTA,
        CONH1.CP04_PLACA_VEICULO,
        CONH1.CP04_ID_TRANSPORTADOR,
        AGENDA_CONH.CP04I_DT_CRIACAO AS AGENDA_CRIACAO,
        CONH1.CP04_DT_DIGITACAO AS CRIACAO_CONHECIMENTO,
        CONH1.CP04_DT_PESO_INICIAL AS PESO_INICIAL,
        DOCA.WM01B_DT_LANCAMENTO_DOCA AS INICIO_CARREGAMENTO,
        EXPED.WM10A_DT AS FINAL_CARREGAMENTO,
        CONH1.CP04_DT_PESO_FINAL AS PESO_FINAL,
        CONH2.CP04B_DT_SAIDA AS SAIDA,
        ACERTO1.CP58_DT AS CHEGADA_CD,
        ISNULL(CONVERT(CHAR(19), DEV.INICIO_DEVOLUCAO, 120), 'Não houve devolução') AS INICIO_DEVOLUCAO,
        ISNULL(CONVERT(CHAR(19), DEV.FINAL_DEVOLUCAO, 120), 'Não houve devolução') AS FINAL_DEVOLUCAO,
        ACERTO1.CP58_DT AS INICIO_ACERTO,
        ACERTO1.CP58_DT_FINALIZACAO AS FINAL_ACERTO
    FROM COMPRAS..CP04_CONHECIMENTO_TRANSPORTE CONH1 WITH(NOLOCK)
    JOIN CADASTRO..CD94_VEICULO VEIC WITH(NOLOCK)
        ON VEIC.CD94_ID = CONH1.CP04_ID_VEICULO
        AND VEIC.CD94_ATIVO = 1
        AND VEIC.CD94_CLASSIFICACAO <> 3
    JOIN CADASTRO..CD93_MOTORISTA MOTO WITH(NOLOCK)
        ON MOTO.CD93_ID = CONH1.CP04_ID_MOTORISTA
        AND MOTO.CD93_ATIVO = 1
    JOIN CADASTRO..CD23_FILIAL FILIAL WITH(NOLOCK)
        ON FILIAL.CD23_ID = CONH1.CP04_ID_FILIAL
    LEFT JOIN COMPRAS..CP04I_AGENDA_CRIAR_CONHECI AGENDA_CONH WITH(NOLOCK)
        ON AGENDA_CONH.CP04I_ID_CONHECIMENTO = CONH1.CP04_ID
    LEFT JOIN WMSCD..WM01B_DOCA_CONHECIMENTO DOCA WITH(NOLOCK)
        ON DOCA.WM01B_ID_CONHECIMENTO = CONH1.CP04_ID
    LEFT JOIN WMSCD..WM10A_EXPED_CONHECIMENTO EXPED WITH(NOLOCK)
        ON EXPED.WM10A_ID_DOCA_CONHECIMENTO = DOCA.WM01B_ID
    LEFT JOIN COMPRAS..CP04B_CONHECIMENTO_TRANSP_GASTO CONH2 WITH(NOLOCK)
        ON CONH2.CP04B_ID_CONHECIMENTO = CONH1.CP04_ID
    LEFT JOIN COMPRAS..CP58_CONHECIMENTO_ACERTO ACERTO1 WITH(NOLOCK)
        ON ACERTO1.CP58_ID_CONHECIMENTO = CONH1.CP04_ID
    LEFT JOIN COMPRAS..CP61_CONHECIMENTO_DEVOLUCAO CONH3 WITH(NOLOCK)
        ON CONH3.CP61_ID_CONHECIMENTO_ORIGEM = CONH1.CP04_ID
    LEFT JOIN Devolucao DEV
        ON DEV.LG317_ID_CONHECIMENTO = CONH3.CP61_ID_CONHECIMENTO_DEVOLUCAO
    WHERE CONH1.CP04_DT_DIGITACAO >= DATEADD(DAY, -:dias, GETDATE())
        AND CONH1.CP04_ID_FILIAL IN :filiais
        AND CONH1.CP04_STATUS IN :status
        AND CONH1.CP04_ID_TIPO = :tipo
        AND (:placa IS NULL OR CONH1.CP04_PLACA_VEICULO = :placa)
    """,
            countQuery = """
    SELECT COUNT_BIG(1)
    FROM COMPRAS..CP04_CONHECIMENTO_TRANSPORTE CONH1 WITH(NOLOCK)
    WHERE CONH1.CP04_DT_DIGITACAO >= DATEADD(DAY, -:dias, GETDATE())
        AND CONH1.CP04_ID_FILIAL IN :filiais
        AND CONH1.CP04_STATUS IN :status
        AND CONH1.CP04_ID_TIPO = :tipo
        AND (:placa IS NULL OR CONH1.CP04_PLACA_VEICULO = :placa)
        AND EXISTS (
            SELECT 1 FROM CADASTRO..CD94_VEICULO VEIC WITH(NOLOCK)
            WHERE VEIC.CD94_ID = CONH1.CP04_ID_VEICULO
              AND VEIC.CD94_ATIVO = 1
              AND VEIC.CD94_CLASSIFICACAO <> 3
        )
        AND EXISTS (
            SELECT 1 FROM CADASTRO..CD93_MOTORISTA MOTO WITH(NOLOCK)
            WHERE MOTO.CD93_ID = CONH1.CP04_ID_MOTORISTA
              AND MOTO.CD93_ATIVO = 1
        )
    """,
            nativeQuery = true)
    Page<ConhecimentoProjection> buscarConhecimentos(
            @Param("filiais") List<String> filiais,
            @Param("dias") int dias,
            @Param("status") List<Integer> status,
            @Param("tipo") int tipo,
            @Param("placa") String placa,
            Pageable pageable
    );
}